// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordAPI.Data;

#nullable disable

namespace RecordAPI.Data.Migrations
{
    [DbContext(typeof(RecordDbContext))]
    [Migration("20230107112501_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("RecordAPI.Data.Record", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("RecordId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            RecordId = 1,
                            Description = "Post 1 description :)",
                            Title = "Post 1"
                        },
                        new
                        {
                            RecordId = 2,
                            Description = "Post 2 description :)",
                            Title = "Post 2"
                        },
                        new
                        {
                            RecordId = 3,
                            Description = "Post 3 description :)",
                            Title = "Post 3"
                        },
                        new
                        {
                            RecordId = 4,
                            Description = "Post 4 description :)",
                            Title = "Post 4"
                        },
                        new
                        {
                            RecordId = 5,
                            Description = "Post 5 description :)",
                            Title = "Post 5"
                        },
                        new
                        {
                            RecordId = 6,
                            Description = "Post 6 description :)",
                            Title = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
